---
dataset:
  dataset: vg
  splitname: compositional-split-natural
  train_only: true
model_params:
  emb_type: ft+w2v
  nhiddenlayers: 0
  nlayer: 2
  alpha: 0.4

training:
  batch_size: 256
  lr: 5.0e-05
  lrg: 5.0e-06 # Learning rete for image backbone if fine-tune the backbone
  cosine_scale: 0.05
  max_epochs: 20
  test_batch_size: 2048
  update_image_features: false # Fine tune the image backbone?
  update_word_features: true
