dataset:
  dataset: vg_2
  splitname: compositional-split-natural
  train_only: true
model_params:
  alpha: 0.4
  emb_type: ft+w2v
  nhiddenlayers: 0
  nlayer: 2
training:
  batch_size: 256
  cosine_scale: 0.05
  lr: 1.0e-05
  lrg: 5.0e-06
  max_epochs: 500
  test_batch_size: 2048
  update_image_features: false
  update_word_features: true
